language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: ff1QGTKwVjGR2sEv0S9hzQCumOaO6L1bt/wVpajSztB6Zz2PYprOspNFg0mobbAOeEvmIbrddCNU3xGCcPIfTTM2HrtZ0nbFpKN75r4F3kDwv0BEpzwHNDC9scl1pHmhVOWn1hdo+RBEK7ixRVN4zDP7bqVSJggi2cJVRyFyTqz5GwWxMpHZvkexm09VjEajXxOdvOUeSbSNDnK9/0sHT38tue30hOt9QGOKJbJ3QTS4ThqkUAuQoGtYZPy1pX5wwPZfNyIlick8QwrY6mPOQDkPcHwfmzeW1wxnh+ok1tKKfOiGwNlBnrctvLUhkBu/PqIWURDdrdeWfhrZLtgNpn/5CUgOapJ7exDz6sGhkOXvKLy79dp6dzgNthoESRYGk6kfzPJZiyPmIZmQd8vjvWcdHfsNEGJfYg2BBeqmc6ZRSSnbxmtrFb8zZUab1eltQupqGB+YlWfoSzFQoKzeW/+SfJA4noP04gsahfnxTIZcRFTMXL7a5FYVpVKbxl+XbNIkreWizSsqAomwGTypoDgn7d9NraYEwWFDATjfPGu+QGcbKC7bWCZpsz/OhaFKqr6RWCiUFKPbWkipQlH/c3Xl2Tme3+kStJSQIe4AVY0vWjkqCPsAqBJy72saB05g5Zo+1y5Q9+xFsHs0VUfhss6VW3yKNE3BJ5aYzU8uFX8=
  - secure: G+P/ZCJ3/M4zLEFpRRdRh+FMYyh7IEcR87Nxydm+7G9fWJvfJkV35ylFOsS+mYhpBuSsWzzddqj6JUiSgMe3QL/4Pzs2lMQAes1Lk77VeyLhkIBVMZiMeOkdt1hZiM8N7SYJZbKm7UsGNb6wUoKKcz6dnKS15Ile/qNmgd6Lxj7Jj4jqh7yO9lv6KPXE5C9Hpd2A9VoC/ghBm/a3titPeviIrShrVvcW1iHD7RkGqb4o6QAuFxEVS8omuCrMwLjFQgnl+REK9Lv/TpPlgLle9QpRjJdL9fCke5SycG/X26jXXunGw2ErKTUnFy9hGE6fdqO/7e90fRW48zoHzFulrosS+4taZXh5z/Kkjexm9dycp6lvULNLDJMpb7zlnPNQeS7Te33FnPgJYbpnTFj6ZU0JlZpsdJ+AVuzWID+3w+sL2U9wWGdromGszgOsygkY44/oEZP8W5IoPueSk6XWQuI25m1FB3JHhbj0gJupv8NulHybqIJXsShCH389wb11hdcL0esVxtN1agy9G57hWXTEceg23ecQHGwqZoKlTNGrwaNfbB945zBFT+uCaV+2d6wEIbAzi1vqXh90ygxYWN+dTs7x6grpV9/aio4b9mEAYCLNN0ePzW1xlajBmER485GvMAR8Ovd+MCIj5KWOVlPWRaXx3+5UQsL3H3U3g68=
